env:
  node: true
  es2021: true
extends:
  - standard
plugins:
  - no-autofix
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  prefer-const: off
  no-autofix/prefer-const: warn
  object-shorthand:
    - warn
    - never
